# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  # build:
  # #...
  deploy:
    machine: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST "echo Hello, World!"

workflows:
  build-and-deploy:
    jobs:
      # - build
      - deploy:
          # requires:
          #   - build # only deploy once build job has completed
          filters:
            branches:
              only: main # only deploy on the main branch
